PREFIX p: <http://pronom.nationalarchives.gov.uk/#>
PREFIX p2: <http://nationalarchives.gov.uk/pronom/ExternalSignature/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?e ?s ?p ?o
WHERE {
    ?s p:ExternalSignature ?es ;
       ?p ?o .
    ?es p:Signature ?e .
}
ORDER BY ?s ?p
